#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
misaki2c.py - Build a minimal Japanese 8x8 glyph table for the UV-K1 / UV-K5 V3
firmware from the Misaki Gothic BDF font.

Only the characters actually used by the firmware sources are embedded, which
keeps the flash cost at a few kilobytes instead of ~57 kB for the full JIS
level 1+2 set.

Misaki font (c) Num Kadoma - https://littlelimit.net/misaki.htm
"These fonts are free softwares. Unlimited permission is granted to use, copy,
 and distribute it, with or without modification, either commercially and
 noncommercially."
"""

import argparse
import os
import re
import sys

FBB_RE = re.compile(r"^FONTBOUNDINGBOX\s+(-?\d+)\s+(-?\d+)\s+(-?\d+)\s+(-?\d+)")


def parse_bdf(path):
    """Return {codepoint: [8 rows of 8 bits, MSB = leftmost pixel]}."""
    glyphs = {}
    fbb = None
    cp = None
    bbx = None
    bitmap = None
    with open(path, "r", encoding="latin-1") as fh:
        for line in fh:
            line = line.rstrip("\r\n")
            if fbb is None:
                m = FBB_RE.match(line)
                if m:
                    fbb = tuple(int(v) for v in m.groups())
                    continue
            if line.startswith("ENCODING "):
                cp = int(line.split()[1])
            elif line.startswith("BBX "):
                bbx = tuple(int(v) for v in line.split()[1:5])
            elif line == "BITMAP":
                bitmap = []
            elif line == "ENDCHAR":
                if cp is not None and bbx is not None and bitmap is not None:
                    glyphs[cp] = render_cell(fbb, bbx, bitmap)
                cp, bbx, bitmap = None, None, None
            elif bitmap is not None and line:
                bitmap.append(line.strip())
    return glyphs


def render_cell(fbb, bbx, bitmap):
    """Place a BDF glyph into a fixed 8x8 cell, returning 8 row bytes."""
    fbb_w, fbb_h, fbb_x, fbb_y = fbb
    w, h, xoff, yoff = bbx
    cell = [0] * 8
    # top row of the font bounding box, in font coordinates
    fbb_top = fbb_y + fbb_h - 1
    glyph_top = yoff + h - 1
    row0 = fbb_top - glyph_top          # first bitmap row inside the cell
    col0 = xoff - fbb_x                 # left shift inside the cell
    nbytes = (w + 7) // 8
    for i, hexrow in enumerate(bitmap[:h]):
        y = row0 + i
        if not (0 <= y < 8):
            continue
        value = int(hexrow, 16)
        # left-align the row into an 8 bit value
        value >>= (nbytes * 8 - w) if nbytes * 8 > w else 0
        row = 0
        for bit in range(w):
            if (value >> (w - 1 - bit)) & 1:
                x = col0 + bit
                if 0 <= x < 8:
                    row |= 0x80 >> x
        cell[y] |= row
    return cell


def to_columns(cell):
    """Rows (MSB = left) -> 8 column bytes, bit0 = top pixel (ST7565 page order)."""
    cols = []
    for x in range(8):
        b = 0
        for y in range(8):
            if (cell[y] >> (7 - x)) & 1:
                b |= 1 << y
        cols.append(b)
    return cols


def collect_codepoints(paths):
    """Every non-ASCII character appearing in a string literal of the sources."""
    used = set()
    for path in paths:
        # some upstream files carry latin-1 accents in comments; those bytes
        # are not valid UTF-8, so decode leniently and only trust well formed
        # multi byte sequences
        with open(path, "r", encoding="utf-8", errors="ignore") as fh:
            text = fh.read()
        for literal in re.findall(r'"((?:[^"\\\n]|\\.)*)"', text):
            for ch in literal:
                if ord(ch) > 0x7F:
                    used.add(ord(ch))
    return used


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--bdf", required=True)
    ap.add_argument("--scan", nargs="+", required=True,
                    help="source files to scan for Japanese string literals")
    ap.add_argument("--out-c", required=True)
    ap.add_argument("--out-h", required=True)
    args = ap.parse_args()

    glyphs = parse_bdf(args.bdf)
    used = sorted(collect_codepoints(args.scan))
    missing = [cp for cp in used if cp not in glyphs]
    if missing:
        sys.stderr.write("missing glyphs: %s\n" %
                         " ".join("U+%04X(%s)" % (c, chr(c)) for c in missing))
        return 1

    lines = []
    lines.append("// Generated by tools/lang_ja/misaki2c.py - do not edit by hand.")
    lines.append("// Glyphs from the Misaki Gothic 8x8 font (c) Num Kadoma,")
    lines.append("// https://littlelimit.net/misaki.htm - free for any use.")
    lines.append("")
    lines.append('#include "font_ja.h"')
    lines.append("")
    lines.append("#ifdef ENABLE_LANG_JA")
    lines.append("")
    lines.append("const uint16_t gFontJaIndex[%d] =" % len(used))
    lines.append("{")
    for i in range(0, len(used), 8):
        chunk = used[i:i + 8]
        lines.append("    " + " ".join("0x%04X," % c for c in chunk) +
                     "  // " + "".join(chr(c) for c in chunk))
    lines.append("};")
    lines.append("")
    lines.append("const uint8_t gFontJa[%d][8] =" % len(used))
    lines.append("{")
    for cp in used:
        cols = to_columns(glyphs[cp])
        lines.append("    {" + ", ".join("0x%02X" % b for b in cols) +
                     "},  // U+%04X %s" % (cp, chr(cp)))
    lines.append("};")
    lines.append("")
    lines.append("const uint16_t gFontJaCount = %d;" % len(used))
    lines.append("")
    lines.append("#endif")
    lines.append("")

    os.makedirs(os.path.dirname(args.out_c), exist_ok=True)
    with open(args.out_c, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines))

    sys.stderr.write("font_ja: %d glyphs, %d bytes of table\n" %
                     (len(used), len(used) * 10))
    return 0


if __name__ == "__main__":
    sys.exit(main())
